# Generated by Django 5.0.2 on 2024-03-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenApi', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
